#pragma once
#ifndef BEARDSERVER_CONFIG_H
#define BEARDSERVER_CONFIG_H

#define BEARDSERVER_PORT 42069
#define BEARDSERVER_ADDR "127.0.0.1"

#define BEARDSERVER_LISTEN_SOCKET_BACKLOG	SOMAXCONN
#define BEARDSERVER_HEARTBEAT_MS_INTERVAL	15000
#define BEARDSERVER_MAX_TIMEOUT_MS			30000

#define BEARDSERVER_MS_PER_UPDATE 33

#endif // !BEARDSERVER_CONFIG_H
